global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      # Usamos el nombre del servicio definido en tu docker-compose
      - targets: ["otel-collector:8889"]

  # OPCIONAL: Si alguna API no usa el collector y quieres leerla directo:
  # - job_name: 'external-apis'
  #   static_configs:
  #     - targets: ['api-dev.altasg2.org:9464'] # API externa
